sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - $HOME/ocular.phar
    - $HOME/phpDocumentor.phar

env:
  global:
    - CODE_COVERAGE="0"
    - PHPDOC="0"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - CODE_COVERAGE="1"
    - php: 7.0
      env:
        - CODE_COVERAGE="1"
        - PHPDOC="1"
    - php: 7.1
      env:
        - CODE_COVERAGE="1"
    - php: 7.2
      env:
        - CODE_COVERAGE="1"
    - php: 7.3
      env:
        - CODE_COVERAGE="1"
    - php: nightly

    # HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: nightly

install:
  - if [ "${CODE_COVERAGE}" == "0" ]; then
      phpenv config-rm xdebug.ini || return 0;
    fi
  - if [ "${CODE_COVERAGE}" == "1" ]; then
      wget -q -N -t 3 --retry-connrefused 'https://scrutinizer-ci.com/ocular.phar' || return 0;
    fi
  - if [ "${PHPDOC}" == "1" ]; then
      wget -q -N -t 3 --retry-connrefused 'https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar' || return 0;
      composer require --no-update --dev "evert/phpdoc-md:~0.2.0" || return 0;
    fi
  - composer install -n

script:
  - if [ "$CODE_COVERAGE" == "1" ]; then
      php -d 'zend.assertions=1' vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover;
    else
      php -d 'zend.assertions=1' vendor/bin/phpunit --verbose;
    fi

after_script:
  - if [ "${CODE_COVERAGE}" == "1" ]; then
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
  - if [ "${PHPDOC}" == "1" ]; then
      git clone "https://${CI_USER_TOKEN}@github.com/marc-mabe/php-enum.wiki.git" &&
      php phpDocumentor.phar -d src -t docs/ --template="xml" &&
      php vendor/bin/phpdocmd --lt '%c' --index 'Home.md' docs/structure.xml php-enum.wiki/ &&
      cp php-enum.wiki/Home.md php-enum.wiki/_Sidebar.md &&
      cd php-enum.wiki/ &&
      git add . &&
      git commit -m "auto generated PHP doc" &&
      git push origin master:master;
    fi

notifications:
  email: false
